name: Build and publish to PyPI

on:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip cibuildwheel build twine

      - name: Backup original setup.py
        run: python -c "import shutil; shutil.copyfile('setup.py', 'setup_original.py')"

      - name: Build compiled wheels with MyPyC
        env:
          CIBW_BEFORE_ALL: "copy setup_mypyc.py setup.py"
#          CIBW_SKIP: pp*  # Disable PyPy builds explicitly since we don't need them
        run: cibuildwheel --output-dir wheelhouse

      - name: Restore original setup.py
        run: python -c "import shutil; shutil.copyfile('setup_original.py', 'setup.py')"

      - name: Build sdist
        run: python setup.py sdist --dist-dir wheelhouse

      - name: Build pure Python wheel
        run: python -m build --wheel --outdir wheelhouse

      - name: Upload to Test PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          python -m pip install twine
          twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing wheelhouse/*

      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: wheelhouse/*
