name: Build and publish to PyPI

on:
  release:
    types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install --upgrade pip cibuildwheel twine

      - name: Build wheels
        #env:
          # If using a custom build, you can set these:
          # CIBW_BEFORE_BUILD: "pip install mypy"
          # CIBW_BUILD: "cp310-*"
        run: |
          cibuildwheel --output-dir wheelhouse

      - name: Build sdist
        run: |
          python setup.py sdist --dist-dir wheelhouse

      - name: Upload to PyPI
        #env:
        #  TWINE_USERNAME: __token__
        #  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        #run: |
        #  python -m pip install twine
        #  twine upload --skip-existing wheelhouse/*
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          python -m pip install twine
          twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing wheelhouse/*
      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: wheelhouse/*
